import '../models/post_model.dart';

final List<Post> kdramaPosts = [
  Post(    username: "kdrama_queen",
    userImage: "https://i.pravatar.cc/150?u=1",
    dramaTitle: "Business Proposal",
    postImage: "https://wallpapers.com/images/hd/business-proposal-kdrama-poster-x0rod0gmpuznd9bz.jpg",
    caption: "The chemistry in this scene was unmatched! 💍 #businessproposal #kdrama",
    likes: 4500,
    audioName: "Love, Maybe - MeloMance",
  ),
  Post(
    username: "oppa_central",
    userImage: "https://i.pravatar.cc/150?u=2",
    dramaTitle: "Twenty-Five Twenty-One",
    postImage: "https://images.justwatch.com/poster/261793906/s718/twenty-five-twenty-one.%7Bformat%7D",
    caption: "This show broke my heart into pieces. 😭 #2521 #namjoo-hyuk",
    likes: 12800,
    audioName: "Original Sound - DramaLover",
  ),
  Post(
    username: "vincenzo_fan",
    userImage: "https://i.pravatar.cc/150?u=3",
    dramaTitle: "Vincenzo",
    postImage: "https://tse4.mm.bing.net/th/id/OIP.eKpdBiuLe0MKAgkiXgQhqAHaKX?rs=1&pid=ImgDetMain&o=7&rm=3",
    caption: "Corn Salad! The legend is back. 🍷🔥 #vincenzo #songjoongki",
    likes: 9200,
    audioName: "Vincenzo Theme - OST",
  ),
  Post(
    username: "iu_fan_forever",
    userImage: "https://i.pravatar.cc/150?u=9",
    dramaTitle: "When Life Gives You Tangerines",
    postImage: "https://i.mydramalist.com/DkJ45N_3f.jpg",
    caption: "IU and Park Bo-gum in one frame? My heart can't take this! 🍊✨ #WhenLifeGivesYouTangerines #IU #ParkBoGum",
    likes: 25400,
    audioName: "Jeju Island - Folk Version",
  ),
  Post(
    username: "sol_sunjae_fan",
    userImage: "https://i.pravatar.cc/150?u=12",
    dramaTitle: "Lovely Runner",
    postImage: "https://static1.srcdn.com/wordpress/wp-content/uploads/2024/05/lovely-runner-2024.jpg",
    caption: "Would you travel back in time to save the person you love? 🕒💛 This drama is pure perfection! #LovelyRunner #ByeonWooSeok #KimHyeYoon",
    likes: 32100,
    audioName: "Sudden Shower - ECLIPSE",
  ),
];
